spring:
  jpa.hibernate.ddl-auto: create-drop
  jackson.serialization.INDENT_OUTPUT: true
server:
  contextPath: /pln
  port: 8090

urls:
  prosite: http://prosite.expasy.org/cgi-bin/prosite/PSScan.cgi?sig=%s&lineage=9606&db=sp&output=json
resources:
  mapping: /psi-mod/mapping.csv

---
spring:
  profiles: default
  datasource:
    url: jdbc:h2:mem:AZ;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

---
spring:
  profiles: mysql
  datasource:
    url: jdbc:mysql://localhost/pilincs
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password:
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect